## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [32]:
import numpy as np
print(np.__version__)


2.2.3


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [ ]:
import numpy as np
arr_bool = np.array = ([True, False, True, False])
print(arr_bool)

[True, False, True, False]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
arr_bool = a > 2
print(arr_bool)  


[False False  True  True  True]


In [30]:

import numpy as np

arr_true = np.ones(5, dtype=bool)
print(arr_true)   # [ True  True  True  True  True]


[ True  True  True  True  True]


In [31]:
import numpy as np

arr_false = np.zeros(5, dtype=bool)
print(arr_false)  # [False False False False False]


[False False False False False]


### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [ ]:
import numpy as np
arr = np.array([2, 3, 5, 7, 8, 9, 11])
le = arr % 2 != 0
MangSoLe = arr[le]
print(MangSoLe)

[ 3  5  7  9 11]


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [ ]:
import numpy as np
arr = np.array([1, 2, 3,4, 5, 6, 7])
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1]


### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr1 = np.where(arr % 2 != 0, -1, arr)
print(arr)
print(arr1)

[1 2 3 4 5 6 7]
[-1  2 -1  4 -1  6 -1]


### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = arr.reshape(3, 3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.column_stack((a, b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
p1 = np.repeat(a, 3)
p2 = np.tile(a, 3)
b = np.concatenate((p1, p2))
print(b)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [1]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c= np.intersect1d(a, b)
print(c)

[2 4]


In [33]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

mask = np.isin(a, b)   
c = a[mask]
print(np.unique(c))   


[2 4]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a, b)
print(c)   


[1 2 3 4]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [4]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

C = np.where(a == b)
print(C)


(array([1, 3, 5, 7]),)


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [5]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])


r = a[(a >= 5) & (a <= 10)]
print(r)


[ 6  9 10]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [6]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

arr[:, [0,2]] = arr[:, [2,0]]

print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [8]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)


arr[[0,2], :] = arr[[2,0], :]

print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [7]:
import numpy as np

arr = np.arange(12).reshape(4,3)
print(arr)

r= arr[::-1]
print(r)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [9]:
import numpy as np

arr = np.arange(12).reshape(4,3)
print(arr)

r = arr[:, ::-1]
print(r)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [10]:
import numpy as np

arr = np.random.uniform(5, 10, size=(2,3))
print(arr)


[[6.79188326 6.63275817 9.10841585]
 [9.89387518 7.45446527 5.54148828]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [11]:
import numpy as np

arr = np.random.random((2,3)) * 10
np.set_printoptions(precision=3)

print(arr)


[[2.423 6.255 5.044]
 [7.96  5.474 8.319]]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [12]:
import numpy as np

arr = np.array([1.23e10, 2.34e-10, 123456789])
np.set_printoptions(suppress=True)

print(arr)


[1.230e+10 2.340e-10 1.235e+08]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [13]:
import numpy as np

arr = np.arange(100)  # mảng 0..99
np.set_printoptions(threshold=np.inf)

print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [16]:
import numpy as np

mang = np.array([1, 2, 3, 4, 5])

trung_binh = np.mean(mang)    
trung_vi = np.median(mang)   
do_lech_chuan = np.std(mang)   

print("Trung binh:", trung_binh)
print("Trung vi:", trung_vi)
print("Do lech chuan:", do_lech_chuan)


Trung binh: 3.0
Trung vi: 3.0
Do lech chuan: 1.4142135623730951


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [15]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)


[0.   0.25 0.5  0.75 1.  ]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [20]:
import numpy as np

def softmax(x, axis=-1):
    x = np.asarray(x)
    xs = x - np.max(x, axis=axis, keepdims=True)
    exps = np.exp(xs)
    return exps / np.sum(exps, axis=axis, keepdims=True)

v = np.array([2.0, 1.0, 0.1])
print(softmax(v))

m = np.array([[1., 2., 3.],
              [1., 2., 3.]])
print(softmax(m, axis=1))


[0.659 0.242 0.099]
[[0.09  0.245 0.665]
 [0.09  0.245 0.665]]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [21]:
import numpy as np

rng = np.random.default_rng(0)
a = np.arange(100)
idx = rng.choice(len(a), size=20, replace=False)  # 20 vị trí ngẫu nhiên, không trùng
a[idx] = 0
print(a)


[ 0  0  2  0  4  5  0  7  8  9 10 11 12 13 14  0 16 17 18 19 20 21  0 23
 24 25  0 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41  0 43 44 45  0 47
 48 49 50 51  0  0 54  0 56  0 58  0 60  0 62 63 64 65 66 67  0 69  0 71
 72  0 74 75 76 77 78 79 80 81 82  0 84 85 86 87 88 89 90 91  0  0 94 95
 96 97 98 99]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [22]:
import numpy as np

a = np.array([[4.2, 0.3, 1.6],
              [5.1, 2.2, 1.7],
              [3.9, 1.8, 1.4],
              [2.0, 0.5, 2.2]])

mask = (a[:, 2] > 1.5) & (a[:, 0] < 5.0)   
f = a[mask]
print(f)


[[4.2 0.3 1.6]
 [2.  0.5 2.2]]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [23]:
import numpy as np

a = np.array([[1,  2,  3],
              [2,  4,  6],
              [3,  6,  9],
              [4,  8, 12]], dtype=float)

col_i, col_j = 0, 1
r = np.corrcoef(a[:, col_i], a[:, col_j])[0, 1]
print("He so tuong quan Pearson:", r)


He so tuong quan Pearson: 1.0


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [24]:
import numpy as np

a = np.array([[3, 7],
              [1, 5],
              [2, 6]])

col = 0                   
a_sorted = a[a[:, col].argsort()]         

print(a_sorted)


[[1 5]
 [2 6]
 [3 7]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [25]:
import numpy as np

x = np.array([1,2,2,3,3,3,4])

vals, counts = np.unique(x, return_counts=True)
m = vals[counts.argmax()]
print(m)   


3


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [26]:
import numpy as np

a = np.array([5, 12, 35, 8, 27, 100])
o = np.clip(a, 10, 30)
print(o)  


[10 12 30 10 27 30]


### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [27]:
import numpy as np

a = np.array([10, 50, 20, 40, 30])
n = 3

idx = np.argpartition(-a, n-1)[:n]        
idx = idx[np.argsort(-a[idx])]           
print(idx)                               


[1 3 4]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

f = a.flatten()
print(f)  


In [28]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

m = a.ravel()
print(m)  


[1 2 3 4 5 6]
